services:
  discord-bot:
    container_name: discord-bot
    image: java21  # 使用基礎image
    volumes:
      - ./:/app  # 掛載整個專案目錄
      - ./config.properties:/app/config.properties
      - ./logs:/app/logs
    # 需要在容器內先編譯再運行
    command: sh -c "mvn clean package && java -jar target/discord-bot.jar"